#:kivy
#:  import ew kivy.uix.effectwidget

<MusicScreen>:
    EffectWidget:
        effects:[ew.verticalblurEffect(size=10),ew.HorizontalblurEffect(size=10) ]
        FitImages:
            source: 'descarga.png'
    MDBoxLayout:
        orientation:'vertical'
        padding:['10dp','30dp','10dp','50dp']
        SongCover:
            size:(250,250)
            size_hint: None, None
            pos_hint:{'center_x':.5}
            RotatingImage:
                source:'descarga.png'
                radius:[250,]
        Widget:
            size_hint:None,None
            height:'25dp'
        Label:
            text:'song name'
            bold:True
            font_size:'25sp'
            size_hint_y:None
            height: self.texture_size[1]
        Label:
            text:'artist name'
            size_hint_y:None
            height:self.texture_size[1]
        MDBoxLayout:
            Slider:
                id: progress
                color:[.7,0,0,1]
                min:0
                max:100
                value:0
                background_width:'20dp'
                cursor_image:''
                cursor_size:('10dp','10dp')
                value_track_color:[0,0,0,1]
                value_track: True
            MyIcon:
                icon: 'restart'
<MyIcon@MDIconButton>:
    color:[.7,0,0,1]
    size_hint:None, None
    User_font_size:'20sp'
    theme_text_color:'Custom'
    size:('20dp','20dp')
    text_color:[1,1,1,1]
<RotatingImage@FitImage>:
    angle:0
    canvas.before:
        PushMatrix
        Rotate:
            angle: root.angle
            origin:self.center
    canvas.after:
        PopMatrix